name: Terraform CI/CD

on:
  push:
    branches:
      - main
      - dev
  pull_request:

jobs:
  terraform:
    name: Terraform Workflow
    runs-on: ubuntu-latest

    steps:
      # Step 1 - Checkout code
      - name: Checkout
        uses: actions/checkout@v3

      # Step 2 - Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      # Step 3 - Terraform Init
      - name: Terraform Init
        run: terraform -chdir=infra/terraform init

      # Step 4 - Terraform Validate
      - name: Terraform Validate
        run: terraform -chdir=infra/terraform validate

      # Step 5 - Terraform Plan (for non-main branches)
      - name: Terraform Plan
        if: github.ref != 'refs/heads/main'
        run: terraform -chdir=infra/terraform plan

      # Step 6 - Terraform Apply (only on main branch)
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform -chdir=infra/terraform apply -auto-approve
